export const
    TEAM_LIST = 'TEAM_LIST',
    TEAM_LIST_INITIATED = 'TEAM_LIST_INITIATED',
    TEAM_LIST_SUCCESS = 'TEAM_LIST_SUCCESS',
    TEAM_LIST_FAILURE = 'TEAM_LIST_FAILURE',

    GROUP_LIST = 'GROUP_LIST',
    GROUP_LIST_INITIATED = 'GROUP_LIST_INITIATED',
    GROUP_LIST_SUCCESS = 'GROUP_LIST_SUCCESS',
    GROUP_LIST_FAILURE = 'GROUP_LIST_FAILURE',

    CLEAR_STORE = 'CLEAR_STORE'