export const
    TEAM_LIST = 'TEAM_LIST',
    TEAM_LIST_INITIATED = 'TEAM_LIST_INITIATED',
    TEAM_LIST_SUCCESS = 'TEAM_LIST_SUCCESS',
    TEAM_LIST_FAILURE = 'TEAM_LIST_FAILURE',

    CLEAR_STORE = 'CLEAR_STORE'